### PR TITLE
Major Updates

### PR DESCRIPTION
**Pull request by xcodz-dot**
My aim is to write highly documented and formatted code

### Done
* Code linting with Pre-commit (It notifies you if your code is not perfectly formatted)
* rcc dynamic code parser (the current implementation is hardcoded)

### In Work
* rcc code checker (3 Stage Linting)

### TODO
* code check
* code compiler
* pre-processor

### CODE REVIEW

**Review by RealAAbraham — COMMENTED** [review]
Why d'you change from single quotes to double? The PEP clearly states that single quotes are best practice.

**Review by RealAAbraham — APPROVED** [review]

**Comment by xcodz-dot** [comment]
Hello, the thing is please do not merge it now (there is a lot of work that I am doing locally)

And if talked about quotes they were done by tool named `black` which is itself hosted by python software foundation. Also
according to this https://www.python.org/dev/peps/pep-0008/#id28 they say they do not have any recommendation but they suggest to use the double quote to avoid backslashes

**Comment by xcodz-dot** [comment]
I will mark this ready for review once i am done with all the things. I will notify you when I will be ready to merge

**Comment by xcodz-dot** [comment]
Hello @RealAAbraham, I would recommend not modifying rcc.py or any code until all the work is implemented in this PR. 😄

**Comment by xcodz-dot** [comment]
Base Parser is ready:
```python
from rcc.core import syntax

code = """
stdout y;
stdout x;
stdout greeting;
stdout "THIRD HELLO WORLD!";
red "HELLO WORLD!";
green "HELLO WORLD!";
blue "HELLO WORLD!";
yellow "HELLO WORLD!";
magenta "HELLO WORLD!";
cyan "HELLO WORLD!";
ptr 56.8;
x = 56.7;
y = "HELLO WORLD!";
"""
code_parser = syntax.Parser()
code_parser.parse_code(code)
print(code_parser.out)  # You can also use code_parser.raw for getting the python dictionary
```

**Comment by RealAAbraham** [comment]
I am going to look at your changes soon! :) I created a `dev` branch for all contributors! :) Could put your amazing work there, maybe?🙈

**Comment by xcodz-dot** [comment]
sure 😄

**Comment by xcodz-dot** [comment]
I will close it from here

**Pull request closed without merging**
