### PR TITLE
Major Updates Pack 1

### PR DESCRIPTION
**Pull request by xcodz-dot**
Ready to merge (I will be opening new PRs on every new feature i add)

Also setup.py is getting modified to drop support for 3.5 (I need some features from 3.6)

### CODE REVIEW

**Comment by RealAAbraham** [comment]
Could you put this in the dev branch?

**Comment by xcodz-dot** [comment]
Ya i did that, you can merge this for now. I will also be using my library named [denverapi](https://github.com/xcodz-dot/denver) to make the things easy and more beautiful 😄

**Comment by xcodz-dot** [comment]
Hello @RealAAbraham, it seems like you are reimplementing your code. This will make my work nearly not useful beacause i am modifying the main core parsers, linters, compiler, library loader, code checker. (Shall I continue?).

What if you say yes:
* I will get my changes done

What if you say no: (Recommended, cause it will take time)
* I will start a new repo deleting all the stuff which is not by me

**Comment by RealAAbraham** [comment]
Hi @xcodz-dot ! I applaud your contributions, really I do! And I am more than impressed by them! I have just merged them! :)

**Comment by xcodz-dot** [comment]
Thanks, I will be making static code analyzer and colored output compiler within a few days

**Comment by RealAAbraham** [comment]
Perfect! @xcodz-dot

**Pull request merged**
